services:
  postgresdb:
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_postgresdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  webapi:  
    container_name: gestion_proyectos_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__PostgresDatabase=${CONNECTION_STRING}
      - AppSettings__SaltGeneradorHash=${SALT_GENERADOR_HASH}
      - Frontend__Url=http://localhost:9600 #Puerto definido para el frontend
    ports:
      - "9500:8080"
    depends_on:
      postgresdb:
        condition: service_healthy

  gestion_proyectos_web:
    container_name: gestion_proyectos_web
    restart: unless-stopped
    depends_on:
      - webapi
    ports:
      - "9600:80"
volumes:
  postgres_postgresdb:
    name: postgres_postgresdb



