// <auto-generated />
using System;
using GestionProyectos.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801033110_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionProyectos.Domain.Entidades.Columna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Columna");
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entidades.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFinPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("proyectos", (string)null);
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entidades.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColumnaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Orden")
                        .HasColumnType("double precision");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColumnaId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Activo = true,
                            CorreoElectronico = "admin@gestion.com",
                            Nombre = "Administrador",
                            PasswordHash = "$2a$11$zXFOf4l2thtWyxhmcsnDT.wu0iCrCytHQWLz9b15x/n61EWDPuvVS",
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Activo = true,
                            CorreoElectronico = "miembro@gestion.com",
                            Nombre = "Miembro",
                            PasswordHash = "$2a$11$qq0VvS9VOe9LZ2f1uzi8yOheV2XUoWCiVA2OjGJ3As0dS2La/HiES",
                            Rol = 2
                        });
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entidades.Columna", b =>
                {
                    b.HasOne("GestionProyectos.Domain.Entidades.Proyecto", "Proyecto")
                        .WithMany("Columnas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entidades.Tarea", b =>
                {
                    b.HasOne("GestionProyectos.Domain.Entidades.Columna", "Columna")
                        .WithMany("Tareas")
                        .HasForeignKey("ColumnaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Domain.Entidades.Usuario", "Responsable")
                        .WithMany("TareasAsignadas")
                        .HasForeignKey("ResponsableId");

                    b.Navigation("Columna");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entidades.Columna", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entidades.Proyecto", b =>
                {
                    b.Navigation("Columnas");
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("TareasAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
